### ISSUE TITLE
Samba share no longer browsable after running.

### ISSUE THREAD

**Issue by jimbolaya** [lazerl0rd/ScriptWINg#1]
After running the TrackerKiller.bat script, I can no longer get to my Samba share on my Linux box. Other Windows based shares seem to work.

I can go through the script line by line and try to figure it out, but I was hoping you would have a better idea what to try to attempt to restore this.

**Comment by jimbolaya** [comment]
After running the TrackerKiller.bat script, I can no longer get to my Samba share on my Linux box. Other Windows based shares seem to work.

I can go through the script line by line and try to figure it out, but I was hoping you would have a better idea what to try to attempt to restore this.

**Comment by lzlrd** [comment]
Okay, so my first thought is the disabling of NTLM Authentication. Could you try setting both the following DWORDs to "0" and "1" and rebooting each time (I honestly have forgotten the default state of these):

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0\RestrictReceivingNTLMTraffic
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0\RestrictSendingNTLMTraffic
```

**Comment by jimbolaya** [comment]
Setting both to 0 or both to 1 got me access back. Thanks.

**Comment by jimbolaya** [comment]
After further experimentation, setting
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0\RestrictReceivingNTLMTraffic `
to 2 and 
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0\RestrictSendingNTLMTraffic`
to 1 also worked.
